### PR TITLE
Add a template for asp.net core hosted Progressive Web App usign mudblazor

### PR DESCRIPTION
**Pull request by evp55555**
since this repo only includes a template for non-PWA wasm project, this adds a asp.net core hosted PWA wasm mudblazor app

### CODE REVIEW

**Comment by Garderoben** [comment]
Sorry i know its been a very long time, haven't really been looking at my other repos. Do you think you can update this one?

**Comment by evp55555** [comment]
No problem, I updated it to 5.0.14

**Comment by evp55555** [comment]
@Garderoben Are there any more issues?

**Comment by Garderoben** [comment]
> @Garderoben Are there any more issues?

Could you update this again? its been a long time since 5.0.14?
Please tag me again when its done and i merge it!

**Comment by Garderoben** [comment]
Working on this now finally, almost done.

https://user-images.githubusercontent.com/10367109/135731107-207be437-e451-4df2-bd66-ca643f5d63ef.mp4

**Pull request closed without merging**
